### ISSUE TITLE
Error while inject SmsSender

### ISSUE THREAD

**Issue by Warchiefs** [nutnetru/laravel-sms#2] opened 2019-02-15 13:14 UTC
"Argument 1 passed to Nutnet\LaravelSms\SmsSender::__construct() must be an instance of Nutnet\LaravelSms\Contracts\Provider, instance of Illuminate\Log\LogManager given, called in /Users/warchiefs/PhpstormProjects/Glamy/backend/src/vendor/nutnet/laravel-sms/src/ServiceProvider.php on line 27"

I try to inject SmsSender in ServiceProvider:

```
<?php

namespace App\Providers\Sender;

use App\Contracts\Sender\SenderServiceContract;
use App\Services\Sender\SenderServiceRegistry;
use App\Services\Sender\SmsSenderService;
use Illuminate\Support\ServiceProvider;
use Nutnet\LaravelSms\SmsSender;

/**
 * Class SenderServiceProvider
 * @package App\Services\Sender
 */
class SenderServiceProvider extends ServiceProvider
{
    public function register()
    {
        $this->app->singleton(SenderServiceContract::class);
    }

    public function boot(SmsSender $smsSender)
    {
        $this->app->make(SenderServiceRegistry::class)
            ->register('sms', new SmsSenderService($smsSender));
    }
}
```

**Comment by maximkou** [comment] 2019-02-22 10:06
Thanks for the report. I check problem existence soon.

**Comment by maximkou** [comment] 2019-02-22 10:09
@Warchiefs, please attach your `nutnet-laravel-sms` config file, and related env parameters.

**Comment by maximkou** [comment] 2019-03-12 08:32
Closing this issue, because it's not reproduce.

**Closed as completed by maximkou** 2019-03-12 08:32 UTC
